# Generated by Django 2.0.5 on 2018-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
